// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20gkigvcfBF7Q_gASL6ZsIQPywZfDccU',
    appId: '1:742653211814:web:600e5e9d72b894be52b067',
    messagingSenderId: '742653211814',
    projectId: 'fitness-acd11',
    authDomain: 'fitness-acd11.firebaseapp.com',
    storageBucket: 'fitness-acd11.firebasestorage.app',
    measurementId: 'G-6M57GTWFJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCrogGmXEC4HU02rIz1MlDbCexz-iNuw4',
    appId: '1:742653211814:android:bc0f798265b02ee952b067',
    messagingSenderId: '742653211814',
    projectId: 'fitness-acd11',
    storageBucket: 'fitness-acd11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgg33h_zWCvBr66ZwDuQ4JfAWrcfQWPBs',
    appId: '1:742653211814:ios:c42823f0bbac9bb452b067',
    messagingSenderId: '742653211814',
    projectId: 'fitness-acd11',
    storageBucket: 'fitness-acd11.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgg33h_zWCvBr66ZwDuQ4JfAWrcfQWPBs',
    appId: '1:742653211814:ios:c42823f0bbac9bb452b067',
    messagingSenderId: '742653211814',
    projectId: 'fitness-acd11',
    storageBucket: 'fitness-acd11.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC20gkigvcfBF7Q_gASL6ZsIQPywZfDccU',
    appId: '1:742653211814:web:abbff40dac3e1eba52b067',
    messagingSenderId: '742653211814',
    projectId: 'fitness-acd11',
    authDomain: 'fitness-acd11.firebaseapp.com',
    storageBucket: 'fitness-acd11.firebasestorage.app',
    measurementId: 'G-Y53XKDXD7N',
  );
}
